In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv('FypDataset.csv')
dataset

Names  Age Fever Headache PainInBody Nausea Vomiting SkinRash  \
0         Ayaan  NaN    No       No        Yes     No      Yes       No   
1       Ibrahim  NaN   Yes       No        Yes     No      Yes       No   
2          Omar  NaN    No       No         No    Yes      Yes       No   
3          Zayd  NaN    No       No        Yes    Yes       No       No   
4        Liyana  NaN   Yes      Yes        Yes    Yes      Yes      Yes   
...         ...  ...   ...      ...        ...    ...      ...      ...   
2490  Mohyuddin  NaN    No       No         No     No       No       No   
2491     Salman  NaN    No       No         No     No       No       No   
2492       Asad  NaN    No       No         No     No       No       No   
2493       Zain  NaN    No       No         No     No       No       No   
2494     Faisal  NaN    No       No         No     No       No       No   

     RunnyNose Cough SoreThroat Sweating Diarrhea TasteLoss Fatigue  \
0           No   Yes        Yes       No       No        No      No   
1           No    No        Yes       No       No        No      No   
2           No   Yes        Yes       No       No        No      No   
3           No   Yes        Yes       No       No        No     Yes   
4          Yes   Yes         No       No       No        No      No   
...        ...   ...        ...      ...      ...       ...     ...   
2490        No    No         No       No      Yes        No      No   
2491        No    No         No       No      Yes        No      No   
2492        No    No         No       No      Yes        No      No   
2493        No    No         No       No      Yes        No      No   
2494        No    No         No       No      Yes        No      No   

        Disease                                          Medicines  
0         COVID           Arinac, Motilium 10mg, Dicloran, Nuberol  
1         COVID    Panadol Extra, Motilium 10mg, Dicloran, Nuberol  
2         COVID         Arinac, Motilium 10mg, Dicloran, Gravinate  
3         COVID  Arinac, Polymalt 100mg, Dicloran, Gravinate, N...  
4         COVID  Panadol Extra, Nuberol, Piriton, Gravinate, Mo...  
...         ...                                                ...  
2490  PNEUMONIA                                             Flagyl  
2491  PNEUMONIA                                             Flagyl  
2492  PNEUMONIA                                             Flagyl  
2493  PNEUMONIA                                             Flagyl  
2494  PNEUMONIA                                             Flagyl  

[2495 rows x 17 columns]

In [ ]:
dataset = dataset.dropna(subset=['Medicines'])

In [ ]:
x=dataset.iloc[:,2:15].values
y1=dataset.iloc[:,-2].values
y2=dataset.iloc[:,-1].values

In [ ]:
y = np.column_stack((y1, y2))
y

array([['COVID', 'Arinac, Motilium 10mg, Dicloran, Nuberol'],
       ['COVID', 'Panadol Extra, Motilium 10mg, Dicloran, Nuberol'],
       ['COVID', 'Arinac, Motilium 10mg, Dicloran, Gravinate'],
       ...,
       ['PNEUMONIA', 'Flagyl'],
       ['PNEUMONIA', 'Flagyl'],
       ['PNEUMONIA', 'Flagyl']], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
LE_x=LabelEncoder()
for i in range(x.shape[1]):
    x[:, i] = LE_x.fit_transform(x[:, i])

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)
# from sklearn.model_selection import train_test_split
# x_train, x_test, y2_train, y2_test = train_test_split(x, y2, test_size=0.2, random_state=0)

In [ ]:
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import RandomForestClassifier
RF = MultiOutputClassifier(RandomForestClassifier(n_estimators=300,random_state=0))
RF.fit(x_train, y_train)
RF_pred=RF.predict(x_test)

from sklearn.metrics import confusion_matrix, classification_report
for i in range(y_test.shape[1]):
    rf=confusion_matrix(y_test[:,i],RF_pred[:,i])
    print(rf)
    print(f"Classification Report for Output {i+1}:\n")
    print(classification_report(y_test[:, i], RF_pred[:, i]), "\n")

from sklearn.model_selection import cross_val_score
cv_scores = cross_val_score(RF, x, y, cv=5)
print("Cross-validation scores:", cv_scores)
print("Average cross-validation score:", cv_scores.mean())

[[ 90   1   3   3   0]
 [  0 103   1   1   0]
 [  0   0  95   0   0]
 [  4   2   0  85  12]
 [  5   1   0  18  75]]
Classification Report for Output 1:

              precision    recall  f1-score   support

       COVID       0.91      0.93      0.92        97
      DENGUE       0.96      0.98      0.97       105
   INFLUENZA       0.96      1.00      0.98        95
     MALARIA       0.79      0.83      0.81       103
   PNEUMONIA       0.86      0.76      0.81        99

    accuracy                           0.90       499
   macro avg       0.90      0.90      0.90       499
weighted avg       0.90      0.90      0.90       499
 

[[8 0 0 ... 0 0 0]
 [0 6 0 ... 0 0 0]
 [0 0 3 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 1]]
Classification Report for Output 2:

                                                                                                                             precision    recall  f1-score   support

                                 

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_

Cross-validation scores: [0.05811623 0.02805611 0.3246493  0.63654618 0.30321285]
Average cross-validation score: 0.2701161358862303


In [ ]:
RF_pred=RF.predict([[1,1,0,0,1,0,1,1,0,0,1,0,1]])
print("Disease is ", RF_pred)

Disease is  [['PNEUMONIA' 'Piriton, Arinac']]


In [ ]:
# !pip install flask_cors

In [ ]:
from flask import Flask, request, jsonify
import numpy as np
import pickle
from flask_cors import CORS
with open("Model.pkl", "wb") as file:
     pickle.dump(RF, file)

with open("Model.pkl", "rb") as file:
    RF = pickle.load(file)

app = Flask(__name__)
CORS(app, origins=["http://localhost:5173"])

all_symptoms = [
    "fever", "headache", "pain in body", "nausea", "vomiting",
    "skin rash", "runny nose", "cough", "sore throat", "sweating",
    "diarrhea", "taste loss", "fatigue"
]

@app.route('/predict', methods=['POST'])
def predict():
    try:
        data = request.json
        symptoms_input = data['features']
        symptom_features = [0] * len(all_symptoms)

        for symptom in symptoms_input:
            if symptom in all_symptoms:
                index = all_symptoms.index(symptom)
                symptom_features[index] = 1

        input_features = np.array(symptom_features).reshape(1, -1)
        prediction = RF.predict(input_features)

        return jsonify({
    "prediction": prediction[0],
    "input_features": symptom_features
})

    except Exception as e:
        return jsonify({"error": str(e)}), 400

if __name__ == '__main__':
    app.run(debug=True, port=8000)

 * Serving Flask app '__main__'
 * Debug mode: on


INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:8000
INFO:werkzeug:Press CTRL+C to quit
INFO:werkzeug: * Restarting with stat
